config/routes.rb
Fitness::Application.routes.draw do
  root to: 'pages#home'

  ActiveAdmin.routes(self)

  devise_for :users

  get 'users/validate_token' => 'sessions#validate_token', as: :validate_token

  resources :diet_lists do
    resources :diet_items
  end

  resources :main_food_groups, only: [:index, :show]
  resources :food_groups, only: [:index, :show]
  resources :food_logs, except: [:new, :index]

  match 'foods/add_log/:id' => 'foods#add_log', via: [:get, :post], as: :add_food_log
  resources :foods, only: [:index, :show]

  get 'logs' => 'logs#show'
  get 'logs/:date' => 'logs#show', as: :logs_with_date
  get 'pages/home'

  get 'dietitians' => 'dietitians#index', as: :dietitians
  get 'dietitians/users/new' => 'dietitians#users_new', as: :new_dietitian_user
  get 'dietitians/users' =>  'dietitians#users_index', as: :dietitian_user
  get 'dietitians/users/:user_id/logs/:date' => 'logs#show', as: :user_logs_with_date
  get 'dietitians/users/:user_id/lists_to_assign' => 'dietitians#lists_to_assign', as: :lists_to_assign
  get 'dietitians/users/:user_id/assign_diet_list/:diet_list_id' => 'dietitians#assign_diet_list', via: :get, as: :assign_diet_list
  post 'dietitians/users' => 'dietitians#users_create'

end

app/views/pages/home.html.slim
- if user_signed_in?
  - if current_user.has_role? :admin
    = link_to "Admin", admin_root_path
  br/
  br/
  - if current_user.diet_lists.any?
    = render current_user.diet_lists.first
    
br/
= link_to t(:other, scope: [:activerecord, :models, :main_food_group]), main_food_groups_path
br/
= link_to t(:other, scope: [:activerecord, :models, :food_group]), food_groups_path
br/
= link_to t(:other, scope: [:activerecord, :models, :food]), foods_path
- if user_signed_in?
  br/
  = link_to t(:other, scope: [:activerecord, :models, :log]), logs_with_date_path(Date.today)