config/routes.rb
Fitness::Application.routes.draw do
  root to: 'pages#home'

  ActiveAdmin.routes(self)

  devise_for :users

  get 'users/validate_token' => 'sessions#validate_token', as: :validate_token

  resources :diet_lists do
    resources :diet_items
  end

  resources :main_food_groups, only: [:index, :show]
  resources :food_groups, only: [:index, :show]
  resources :food_logs, except: [:new, :index]

  match 'foods/add_log/:id' => 'foods#add_log', via: [:get, :post], as: :add_food_log
  resources :foods, only: [:index, :show]

  get 'logs' => 'logs#show'
  get 'logs/:date' => 'logs#show', as: :logs_with_date
  get 'pages/home'

  get 'dietitians' => 'dietitians#index', as: :dietitians
  get 'dietitians/users/new' => 'dietitians#users_new', as: :new_dietitian_user
  get 'dietitians/users' =>  'dietitians#users_index', as: :dietitian_user
  get 'dietitians/users/:user_id/logs/:date' => 'logs#show', as: :user_logs_with_date
  get 'dietitians/users/:user_id/lists_to_assign' => 'dietitians#lists_to_assign', as: :lists_to_assign
  get 'dietitians/users/:user_id/assign_diet_list/:diet_list_id' => 'dietitians#assign_diet_list', via: :get, as: :assign_diet_list
  post 'dietitians/users' => 'dietitians#users_create'

end

app/models/diet_list.rb
class DietList < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user
  has_many :diet_items, dependent: :destroy

  validates :user_id, :name, presence: true
  after_save :log

  def self.prepared
    find_all_by_user_id(User.first)
  end
  
  protected
    def json_for_log
      to_json(except: [:id, :created_at], include: { diet_items: {only: [:amount, :main_food_group_id]}})
    end

  private
    def log
      diet_list_log = user.diet_list_logs.find_or_initialize_by_created_on(Date.today)
      diet_list_log.diet_list = self.json_for_log
      diet_list_log.save
    end
end

app/controllers/diet_lists_controller.rb
class DietListsController < InheritedResources::Base
  load_and_authorize_resource

  def index
    @diet_lists = current_user.diet_lists
    index!
  end

  def show
    redirect_to diet_list_diet_items_path(@diet_list)
  end

  def show_prepared
    @diet_lists = DietList.prepared
  end

  def update
    update! { diet_list_diet_items_path(@diet_list) }
  end
end

app/views/diet_lists/_diet_list.html.slim
h3= diet_list.name
table.table
  tr
    th= t(:main_food_group, scope: [:activerecord, :attributes, :diet_list])
    th= t(:amount, scope: [:activerecord, :attributes, :diet_list])
    th
    th
    th
  - diet_list.diet_items.each do |diet_item|
    tr
      = render diet_item
  - if diet_list.id
    tr
      = render template: 'restful/actions', locals: { resource: diet_list }
- if current_user and current_user.has_role? :dietitian_of, @user and diet_list.id
  td= link_to t(:assign, scope: :actions), assign_diet_list_path(@user, diet_list)

app/views/diet_lists/_form.html.slim
= semantic_form_for @diet_list do |f|
  = f.input :name
  = f.submit

app/views/diet_lists/edit.html.slim
h1 Diyet Listesi Düzenle
= render 'form'
= link_to t(:show, scope: :actions), @diet_list
=> link_to '<<<', root_path

app/views/diet_lists/index.html.slim
= link_to 'Yeni Diyet Listesi', new_diet_list_path
= render @diet_lists

app/views/diet_lists/new.html.slim
h1 Yeni Diyet Listesi
= render 'form'
=> link_to '<<<', root_path

app/views/diet_lists/show.html.slim
= render @diet_list