config/routes.rb
Fitness::Application.routes.draw do
  root to: 'pages#home'

  ActiveAdmin.routes(self)

  devise_for :users

  get 'users/validate_token' => 'sessions#validate_token', as: :validate_token

  resources :diet_lists do
    resources :diet_items
  end

  resources :main_food_groups, only: [:index, :show]
  resources :food_groups, only: [:index, :show]
  resources :food_logs, except: [:new, :index]

  match 'foods/add_log/:id' => 'foods#add_log', via: [:get, :post], as: :add_food_log
  resources :foods, only: [:index, :show]

  get 'logs' => 'logs#show'
  get 'logs/:date' => 'logs#show', as: :logs_with_date
  get 'pages/home'

  get 'dietitians' => 'dietitians#index', as: :dietitians
  get 'dietitians/users/new' => 'dietitians#users_new', as: :new_dietitian_user
  get 'dietitians/users' =>  'dietitians#users_index', as: :dietitian_user
  get 'dietitians/users/:user_id/logs/:date' => 'logs#show', as: :user_logs_with_date
  get 'dietitians/users/:user_id/lists_to_assign' => 'dietitians#lists_to_assign', as: :lists_to_assign
  get 'dietitians/users/:user_id/assign_diet_list/:diet_list_id' => 'dietitians#assign_diet_list', via: :get, as: :assign_diet_list
  post 'dietitians/users' => 'dietitians#users_create'

end

app/models/food.rb
class Food < ActiveRecord::Base
  extend Enumerize
  extend ActiveModel::Naming
  include PgSearch

  enumerize :weight_type, in: { g: 1, ml: 2 }, default: :g
  pg_search_scope :search_by_name,
    :against => :name,
    :ignoring => :accents,
    :order_within_rank => "foods.name ASC",
    :using => { :tsearch => {
      :prefix => true,
      :dictionary => "turkish" } }

  belongs_to :food_group
  attr_accessible :name, :weight, :food_group_id, :weight_type
  validates :name, :food_group, presence: true
  validates :weight, numericality: { greater_than_or_equal: 0.01 }
  validates :weight_type, numericality: { greater_than: 0, less_than: 3 }
  before_save :downcase_name

  def self.search(query)
    return search_by_name(query) unless query.blank?
    order(:name)
  end

  def name
    UnicodeUtils.titlecase(read_attribute(:name)) if read_attribute(:name)
  end

  private
    def downcase_name
      self.name = UnicodeUtils.downcase(self.name)
    end
end

app/controllers/foods_controller.rb
class FoodsController < InheritedResources::Base
  load_and_authorize_resource
  has_scope :page, default: 1

  def index
    @foods = Food.search(params[:search]).page(params[:page])
    index!
  end

  # TODO: Guess meal from time
  def add_log
    @food_log = current_user.food_logs.build(food_id: params[:id], weight: 1.0,
                                             date: Date.today, meal: :breakfast)
  end
end

app/views/foods/add_log.html.slim
= render template: 'food_logs/_form'

app/views/foods/index.html.slim
h1= t(:other, scope: [:activerecord, :models, :food])
= form_tag foods_path, :method => 'get' do
  p
    = text_field_tag :search, params[:search]
    = submit_tag t(:search, scope: :actions), :name => nil
br/
= paginate @foods
br/
table.table
  tr
    th= t(:name, scope: [:activerecord, :attributes, :food])
    th= t(:weight, scope: [:activerecord, :attributes, :food])
    th= t(:food_group, scope: [:activerecord, :attributes, :food])
    th
  - @foods.each do |food|
    tr
      td= link_to food.name, food_path(food)
      td= food.weight
      td= food.food_group.name
      - if can? :add_log, food
        td= link_to t(:add_log, scope: :actions), add_food_log_path(food)
br/
= link_to '<<<', root_path

app/views/foods/show.html.slim
h1= @food.name
table.table
  tr
    th= t(:weight, scope: [:activerecord, :attributes, :food])
    th= t(:food_group, scope: [:activerecord, :attributes, :food])
    th
  tr
    td= @food.weight
    td= link_to @food.food_group.name
    - if can? :eat, @food
      td= link_to t(:add_log, scope: :actions), add_food_log_path(@food)
br/
= link_to '<<', foods_path