config/routes.rb
Fitness::Application.routes.draw do
  root to: 'pages#home'

  ActiveAdmin.routes(self)

  devise_for :users

  get 'users/validate_token' => 'sessions#validate_token', as: :validate_token

  resources :diet_lists do
    resources :diet_items
  end

  resources :main_food_groups, only: [:index, :show]
  resources :food_groups, only: [:index, :show]
  resources :food_logs, except: [:new, :index]

  match 'foods/add_log/:id' => 'foods#add_log', via: [:get, :post], as: :add_food_log
  resources :foods, only: [:index, :show]

  get 'logs' => 'logs#show'
  get 'logs/:date' => 'logs#show', as: :logs_with_date
  get 'pages/home'

  get 'dietitians' => 'dietitians#index', as: :dietitians
  get 'dietitians/users/new' => 'dietitians#users_new', as: :new_dietitian_user
  get 'dietitians/users' =>  'dietitians#users_index', as: :dietitian_user
  get 'dietitians/users/:user_id/logs/:date' => 'logs#show', as: :user_logs_with_date
  get 'dietitians/users/:user_id/lists_to_assign' => 'dietitians#lists_to_assign', as: :lists_to_assign
  get 'dietitians/users/:user_id/assign_diet_list/:diet_list_id' => 'dietitians#assign_diet_list', via: :get, as: :assign_diet_list
  post 'dietitians/users' => 'dietitians#users_create'

end

app/controllers/dietitians_controller.rb
class DietitiansController < ApplicationController
  include ::DietitiansHelper
  before_filter :authenticate_dietitian!

  def index
  end

  def users_create
    @user = User.create({ password: rand(36**9).to_s(36) }.merge(params[:user]))
    if @user.errors.empty?
      current_user.add_role :dietitian_of, @user
      render 'users_show'
    else
      render 'users_new'
    end
  end

  def users_new
    @user = User.new
  end

  def users_index
    @users = current_user.roles.select { |r| r.name == 'dietitian_of' }.map { |r| User.find(r.resource_id) }
  end

  def assign_diet_list
    user = User.find(params[:user_id])
    diet_list = DietList.find(params[:diet_list_id])
    diet_list = user.use_diet_list(diet_list)
    respond_to do |format|
      format.html { redirect_to user_logs_with_date_path(user, Date.today) }
      format.json { render json: diet_list }
    end
  end

  def lists_to_assign
    @user = User.find(params[:user_id])
    @diet_lists = current_user.diet_lists
    render @diet_lists
  end
end

app/helpers/dietitians_helper.rb
module DietitiansHelper

	def authenticate_dietitian!
	  authenticate_user!
	  unless (current_user.has_role?(:dietitian) or current_user.has_role?(:admin))
      respond_to do |format|
        flash[:alert] = t :only_dietitians, scope: :alert
        format.html { redirect_to root_path }
        format.json { render json: { error: flash[:alert] }, status: 403 }
      end
	  end
	end
end

app/views/dietitians/index.html.slim
| Diyetisyen sayfamiza hoş geldiniz

br/ 
br/


br/
= link_to 'Hazır Diyet Listelerim', diet_lists_path
br/
= link_to 'Kullanıcılar', dietitian_user_path
br/
= link_to 'Kullanıcı ekle', new_dietitian_user_path

br/
br/
br/
= link_to t(:other, scope: [:activerecord, :models, :main_food_group]), main_food_groups_path
br/
= link_to t(:other, scope: [:activerecord, :models, :food_group]), food_groups_path
br/
= link_to t(:other, scope: [:activerecord, :models, :food]), foods_path

app/views/dietitians/users_index.html.slim
table.table
  tr
    th= 'E-posta'
    th
    th
    th
  - @users.each do |user|
    tr
      = render template: 'dietitians/users_show', locals: { user: user }

app/views/dietitians/users_new.html.slim
= @user.errors.full_messages
= semantic_form_for @user, url: dietitian_user_path do |f|
  = f.input :email
  = f.submit

app/views/dietitians/users_show.html.slim
td= user.email
td= link_to 'Geçmiş', user_logs_with_date_path(user, Date.today)
td= link_to 'Diyet Listesi Ata', lists_to_assign_path(user)